// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AuthenticateUser() {
  return window['go']['main']['App']['AuthenticateUser']();
}

export function IsAuthenticated() {
  return window['go']['main']['App']['IsAuthenticated']();
}
